package com.spreetail.expenses.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.OffsetDateTime;

/**
 * JPA entity representing an application user.
 *
 * <p>Maps to the {@code users} table created in Flyway migration V1.
 *
 * <p>IMPORTANT: This entity is NEVER exposed directly in API responses.
 * Always use {@link UserDTO} for external communication.
 * This prevents leaking sensitive data (password_hash) and decouples
 * the API contract from the database schema.
 *
 * <p>Each user can:
 * <ul>
 *   <li>Belong to multiple groups (via group_memberships)</li>
 *   <li>Pay for expenses and owe shares</li>
 *   <li>Make and receive settlement payments</li>
 *   <li>Upload CSV files for import</li>
 * </ul>
 *
 * <p>Note: We don't extend BaseEntity here because the users table
 * has both created_at and updated_at (which BaseEntity provides),
 * but we want explicit control over the column mappings for this
 * security-critical entity.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Auto-generated primary key.
     * Maps to BIGSERIAL in PostgreSQL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Email address — unique login identifier.
     * Used by Spring Security for authentication.
     * Validated with @Email in the registration DTO.
     */
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /**
     * BCrypt-encoded password hash.
     * NEVER exposed in API responses (not in UserDTO).
     * Generated by Spring Security's BCryptPasswordEncoder.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * Display name shown in expense splits, balance summaries,
     * and settlement suggestions.
     * Maps to flatmate names: Aisha, Rohan, Priya, Meera, Sam, Dev.
     */
    @Column(name = "full_name", nullable = false, length = 255)
    private String fullName;

    /**
     * Timestamp when the user account was created.
     * Set automatically on INSERT via @PrePersist.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Timestamp when the user account was last updated.
     * Updated automatically on every save via @PreUpdate.
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * JPA lifecycle callback: sets timestamps on initial creation.
     */
    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback: updates modification timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
